# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/event_configuration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class eventConfigDialog(object):
    def setupUi(self, eventConfigDialog):
        eventConfigDialog.setObjectName("eventConfigDialog")
        eventConfigDialog.setEnabled(True)
        eventConfigDialog.resize(637, 168)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(eventConfigDialog.sizePolicy().hasHeightForWidth())
        eventConfigDialog.setSizePolicy(sizePolicy)
        eventConfigDialog.setMaximumSize(QtCore.QSize(16777215, 168))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        eventConfigDialog.setFont(font)
        self.formLayout = QtWidgets.QFormLayout(eventConfigDialog)
        self.formLayout.setObjectName("formLayout")
        self.eventLabel = QtWidgets.QLabel(eventConfigDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.eventLabel.setFont(font)
        self.eventLabel.setObjectName("eventLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.eventLabel)
        self.eventNameTextLine = QtWidgets.QLineEdit(eventConfigDialog)
        self.eventNameTextLine.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.eventNameTextLine.setFont(font)
        self.eventNameTextLine.setObjectName("eventNameTextLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.eventNameTextLine)
        self.eventDescriptionLabel = QtWidgets.QLabel(eventConfigDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.eventDescriptionLabel.setFont(font)
        self.eventDescriptionLabel.setObjectName("eventDescriptionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.eventDescriptionLabel)
        self.eventDescriptionTextLine = QtWidgets.QLineEdit(eventConfigDialog)
        self.eventDescriptionTextLine.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.eventDescriptionTextLine.setFont(font)
        self.eventDescriptionTextLine.setObjectName("eventDescriptionTextLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.eventDescriptionTextLine)
        self.eventStartLabel = QtWidgets.QLabel(eventConfigDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.eventStartLabel.setFont(font)
        self.eventStartLabel.setObjectName("eventStartLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.eventStartLabel)
        self.eventStartTextLine = QtWidgets.QLineEdit(eventConfigDialog)
        self.eventStartTextLine.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.eventStartTextLine.setFont(font)
        self.eventStartTextLine.setObjectName("eventStartTextLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.eventStartTextLine)
        self.eventEndLabel = QtWidgets.QLabel(eventConfigDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setItalic(False)
        self.eventEndLabel.setFont(font)
        self.eventEndLabel.setObjectName("eventEndLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.eventEndLabel)
        self.eventEndTextLine = QtWidgets.QLineEdit(eventConfigDialog)
        self.eventEndTextLine.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.eventEndTextLine.setFont(font)
        self.eventEndTextLine.setObjectName("eventEndTextLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eventEndTextLine)
        self.saveHL = QtWidgets.QHBoxLayout()
        self.saveHL.setObjectName("saveHL")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.saveHL.addItem(spacerItem)
        self.saveButton = QtWidgets.QPushButton(eventConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.saveButton.setFont(font)
        self.saveButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saveButton.setCheckable(False)
        self.saveButton.setObjectName("saveButton")
        self.saveHL.addWidget(self.saveButton)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.saveHL)

        self.retranslateUi(eventConfigDialog)
        QtCore.QMetaObject.connectSlotsByName(eventConfigDialog)

    def retranslateUi(self, eventConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        eventConfigDialog.setWindowTitle(_translate("eventConfigDialog", "Event Configuration"))
        self.eventLabel.setText(_translate("eventConfigDialog", "Event Name:"))
        self.eventDescriptionLabel.setText(_translate("eventConfigDialog", "Event Description:"))
        self.eventStartLabel.setText(_translate("eventConfigDialog", "Event Start Timestamp:"))
        self.eventEndLabel.setText(_translate("eventConfigDialog", "Event End Timestamp:"))
        self.saveButton.setText(_translate("eventConfigDialog", "Save Event"))

