# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/export_configuration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class exportConfigDialog(object):
    def setupUi(self, exportConfigDialog):
        exportConfigDialog.setObjectName("exportConfigDialog")
        exportConfigDialog.resize(745, 490)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(exportConfigDialog.sizePolicy().hasHeightForWidth())
        exportConfigDialog.setSizePolicy(sizePolicy)
        exportConfigDialog.setMinimumSize(QtCore.QSize(500, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(exportConfigDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(exportConfigDialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeWidget = QtWidgets.QTreeWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.treeWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        self.itemSaved = QtWidgets.QListWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemSaved.sizePolicy().hasHeightForWidth())
        self.itemSaved.setSizePolicy(sizePolicy)
        self.itemSaved.setMinimumSize(QtCore.QSize(100, 0))
        self.itemSaved.setObjectName("itemSaved")
        item = QtWidgets.QListWidgetItem()
        self.itemSaved.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.itemSaved.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.itemSaved.addItem(item)
        self.verticalLayout.addWidget(self.splitter)
        self.exportFileName = QtWidgets.QLineEdit(exportConfigDialog)
        self.exportFileName.setObjectName("exportFileName")
        self.verticalLayout.addWidget(self.exportFileName)
        self.bottomHL = QtWidgets.QHBoxLayout()
        self.bottomHL.setObjectName("bottomHL")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomHL.addItem(spacerItem)
        self.exportFormatLabel = QtWidgets.QLabel(exportConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportFormatLabel.sizePolicy().hasHeightForWidth())
        self.exportFormatLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.exportFormatLabel.setFont(font)
        self.exportFormatLabel.setObjectName("exportFormatLabel")
        self.bottomHL.addWidget(self.exportFormatLabel)
        self.exportFormatComboBox = QtWidgets.QComboBox(exportConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportFormatComboBox.sizePolicy().hasHeightForWidth())
        self.exportFormatComboBox.setSizePolicy(sizePolicy)
        self.exportFormatComboBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.exportFormatComboBox.setFont(font)
        self.exportFormatComboBox.setStyleSheet("")
        self.exportFormatComboBox.setMaxVisibleItems(15)
        self.exportFormatComboBox.setObjectName("exportFormatComboBox")
        self.exportFormatComboBox.addItem("")
        self.exportFormatComboBox.addItem("")
        self.exportFormatComboBox.addItem("")
        self.bottomHL.addWidget(self.exportFormatComboBox)
        self.exportButton = QtWidgets.QPushButton(exportConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportButton.sizePolicy().hasHeightForWidth())
        self.exportButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exportButton.setFont(font)
        self.exportButton.setStyleSheet("")
        self.exportButton.setObjectName("exportButton")
        self.bottomHL.addWidget(self.exportButton)
        self.verticalLayout.addLayout(self.bottomHL)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(exportConfigDialog)
        QtCore.QMetaObject.connectSlotsByName(exportConfigDialog)

    def retranslateUi(self, exportConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        exportConfigDialog.setWindowTitle(_translate("exportConfigDialog", "Export"))
        self.treeWidget.headerItem().setText(0, _translate("exportConfigDialog", "C:"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("exportConfigDialog", "Users"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("exportConfigDialog", "Desktop"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("exportConfigDialog", "Graphs"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).setText(0, _translate("exportConfigDialog", "Red_Team(1/31/20).jpeg"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).setText(0, _translate("exportConfigDialog", "Red_Team(1/25/20).jpeg"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).setText(0, _translate("exportConfigDialog", "Blue_Team(1/24/20).png"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("exportConfigDialog", "Reports"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(0, _translate("exportConfigDialog", "Attack_Report(1/24/20).docx"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("exportConfigDialog", "White Team Eval."))
        self.treeWidget.topLevelItem(0).child(0).child(2).child(0).setText(0, _translate("exportConfigDialog", "Input_documents"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.itemSaved.isSortingEnabled()
        self.itemSaved.setSortingEnabled(False)
        item = self.itemSaved.item(0)
        item.setText(_translate("exportConfigDialog", "Red_Team(1/31/20).jpeg"))
        item = self.itemSaved.item(1)
        item.setText(_translate("exportConfigDialog", "Red_Team(1/25/20).jpeg"))
        item = self.itemSaved.item(2)
        item.setText(_translate("exportConfigDialog", "Blue_Team(1/24/20).png"))
        self.itemSaved.setSortingEnabled(__sortingEnabled)
        self.exportFileName.setText(_translate("exportConfigDialog", "Blue_Team(1/31/20).csv"))
        self.exportFormatLabel.setText(_translate("exportConfigDialog", "Export Format:"))
        self.exportFormatComboBox.setCurrentText(_translate("exportConfigDialog", "CSV"))
        self.exportFormatComboBox.setItemText(0, _translate("exportConfigDialog", "CSV"))
        self.exportFormatComboBox.setItemText(1, _translate("exportConfigDialog", "JPEG"))
        self.exportFormatComboBox.setItemText(2, _translate("exportConfigDialog", "PNG"))
        self.exportButton.setText(_translate("exportConfigDialog", "Export"))

