# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from src.change_configuration import changeConfigDialog
from src.directory_configuration import directoryConfigDialog
from src.event_configuration import eventConfigDialog
from src.export_configuration import exportConfigDialog
from src.filter_configuration import filter_dialog
from src.relationship_configuration import relationshipConfigFrame
from src.team_configuration import teamConfigDialog
from src.vector_configuration import vectorConfigFrame
from src.vector_db_configuration_analyst import vector_db_analyst
from src.vector_db_configuration_lead import vector_db_lead


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(949, 632)
        self.mainWidget = QtWidgets.QWidget(mainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topHL = QtWidgets.QHBoxLayout()
        self.topHL.setObjectName("topHL")
        self.teamButton = QtWidgets.QPushButton(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.teamButton.setFont(font)
        self.teamButton.setObjectName("teamButton")
        self.topHL.addWidget(self.teamButton)
        self.teamButton.clicked.connect(self.show_team_dialog)
        self.eventButton = QtWidgets.QPushButton(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.eventButton.setFont(font)
        self.eventButton.setObjectName("eventButton")
        self.topHL.addWidget(self.eventButton)
        self.eventButton.clicked.connect(self.show_event_dialog)
        self.vectorButton = QtWidgets.QPushButton(self.mainWidget)
        self.vectorButton.setObjectName("vectorButton")
        self.topHL.addWidget(self.vectorButton)
        self.filterButton = QtWidgets.QPushButton(self.mainWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\icons/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterButton.setIcon(icon)
        self.filterButton.setObjectName("filterButton")
        self.topHL.addWidget(self.filterButton)
        self.filterButton.clicked.connect(self.show_filter_dialog)
        self.commitButton = QtWidgets.QPushButton(self.mainWidget)
        self.commitButton.setObjectName("commitButton")
        self.topHL.addWidget(self.commitButton)
        self.syncButton = QtWidgets.QPushButton(self.mainWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\icons/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.syncButton.setIcon(icon1)
        self.syncButton.setObjectName("syncButton")
        self.topHL.addWidget(self.syncButton)
        self.exportButton = QtWidgets.QPushButton(self.mainWidget)
        self.exportButton.setObjectName("exportButton")
        self.topHL.addWidget(self.exportButton)
        self.verticalLayout_3.addLayout(self.topHL)
        self.tabWidget = QtWidgets.QTabWidget(self.mainWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.logFileTab = QtWidgets.QWidget()
        self.logFileTab.setObjectName("logFileTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.logFileTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topVL = QtWidgets.QVBoxLayout()
        self.topVL.setObjectName("topVL")
        self.logFileTableLabel = QtWidgets.QLabel(self.logFileTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logFileTableLabel.sizePolicy().hasHeightForWidth())
        self.logFileTableLabel.setSizePolicy(sizePolicy)
        self.logFileTableLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.logFileTableLabel.setFont(font)
        self.logFileTableLabel.setObjectName("logFileTableLabel")
        self.topVL.addWidget(self.logFileTableLabel)
        self.logFileTable = QtWidgets.QTableWidget(self.logFileTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logFileTable.sizePolicy().hasHeightForWidth())
        self.logFileTable.setSizePolicy(sizePolicy)
        self.logFileTable.setMinimumSize(QtCore.QSize(801, 0))
        self.logFileTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.logFileTable.setObjectName("logFileTable")
        self.logFileTable.setColumnCount(6)
        self.logFileTable.setRowCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.logFileTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.logFileTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.logFileTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.logFileTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.logFileTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.logFileTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.logFileTable.setItem(0, 5, item)
        self.logFileTable.verticalHeader().setSortIndicatorShown(True)
        self.topVL.addWidget(self.logFileTable)
        self.verticalLayout.addLayout(self.topVL)
        self.middleVL = QtWidgets.QVBoxLayout()
        self.middleVL.setObjectName("middleVL")
        self.earTableLabel = QtWidgets.QLabel(self.logFileTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.earTableLabel.sizePolicy().hasHeightForWidth())
        self.earTableLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.earTableLabel.setFont(font)
        self.earTableLabel.setObjectName("earTableLabel")
        self.middleVL.addWidget(self.earTableLabel)
        self.earTable = QtWidgets.QTableWidget(self.logFileTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.earTable.sizePolicy().hasHeightForWidth())
        self.earTable.setSizePolicy(sizePolicy)
        self.earTable.setMinimumSize(QtCore.QSize(0, 0))
        self.earTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.earTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.earTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.earTable.setRowCount(15)
        self.earTable.setObjectName("earTable")
        self.earTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.earTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.earTable.setHorizontalHeaderItem(1, item)
        self.earTable.horizontalHeader().setStretchLastSection(True)
        self.earTable.verticalHeader().setSortIndicatorShown(True)
        self.middleVL.addWidget(self.earTable)
        self.verticalLayout.addLayout(self.middleVL)
        self.middleHL = QtWidgets.QHBoxLayout()
        self.middleHL.setObjectName("middleHL")
        self.chosenFileLabel = QtWidgets.QLabel(self.logFileTab)
        self.chosenFileLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.chosenFileLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chosenFileLabel.setFont(font)
        self.chosenFileLabel.setObjectName("chosenFileLabel")
        self.middleHL.addWidget(self.chosenFileLabel)
        self.chosenFilePathLabel = QtWidgets.QLabel(self.logFileTab)
        self.chosenFilePathLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chosenFilePathLabel.setFont(font)
        self.chosenFilePathLabel.setObjectName("chosenFilePathLabel")
        self.middleHL.addWidget(self.chosenFilePathLabel)
        self.verticalLayout.addLayout(self.middleHL)
        self.bottomHL = QtWidgets.QHBoxLayout()
        self.bottomHL.setObjectName("bottomHL")
        self.directoryButton = QtWidgets.QPushButton(self.logFileTab)
        self.directoryButton.setObjectName("directoryButton")
        self.bottomHL.addWidget(self.directoryButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomHL.addItem(spacerItem)
        self.validateButton = QtWidgets.QPushButton(self.logFileTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validateButton.sizePolicy().hasHeightForWidth())
        self.validateButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.validateButton.setFont(font)
        self.validateButton.setObjectName("validateButton")
        self.bottomHL.addWidget(self.validateButton)
        self.cancelButton = QtWidgets.QPushButton(self.logFileTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.bottomHL.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.bottomHL)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.tabWidget.addTab(self.logFileTab, "")
        self.ogEntryTab = QtWidgets.QWidget()
        self.ogEntryTab.setObjectName("ogEntryTab")
        self.gridLayout = QtWidgets.QGridLayout(self.ogEntryTab)
        self.gridLayout.setObjectName("gridLayout")
        self.logEntryTableWidget = QtWidgets.QTableWidget(self.ogEntryTab)
        self.logEntryTableWidget.setMinimumSize(QtCore.QSize(680, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.logEntryTableWidget.setFont(font)
        self.logEntryTableWidget.setObjectName("logEntryTableWidget")
        self.logEntryTableWidget.setColumnCount(5)
        self.logEntryTableWidget.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        item.setFont(font)
        self.logEntryTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        item.setFont(font)
        self.logEntryTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        item.setFont(font)
        self.logEntryTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        item.setFont(font)
        self.logEntryTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        item.setFont(font)
        self.logEntryTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.logEntryTableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.logEntryTableWidget.setItem(18, 0, item)
        self.logEntryTableWidget.horizontalHeader().setVisible(False)
        self.logEntryTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.logEntryTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.logEntryTableWidget.horizontalHeader().setMinimumSectionSize(60)
        self.logEntryTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.logEntryTableWidget.horizontalHeader().setStretchLastSection(True)
        self.logEntryTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.logEntryTableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.logEntryTableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.ogEntryTab, "")
        self.nodeConfigTab = QtWidgets.QWidget()
        self.nodeConfigTab.setObjectName("nodeConfigTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.nodeConfigTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nodeTopHL = QtWidgets.QHBoxLayout()
        self.nodeTopHL.setObjectName("nodeTopHL")
        self.vectorLabel = QtWidgets.QLabel(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vectorLabel.setFont(font)
        self.vectorLabel.setObjectName("vectorLabel")
        self.nodeTopHL.addWidget(self.vectorLabel)
        self.vectorComboBox = QtWidgets.QComboBox(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.vectorComboBox.setFont(font)
        self.vectorComboBox.setObjectName("vectorComboBox")
        self.vectorComboBox.addItem("")
        self.vectorComboBox.addItem("")
        self.nodeTopHL.addWidget(self.vectorComboBox)
        self.descriptionLabel = QtWidgets.QLabel(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.nodeTopHL.addWidget(self.descriptionLabel)
        self.label = QtWidgets.QLabel(self.nodeConfigTab)
        self.label.setObjectName("label")
        self.nodeTopHL.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.nodeTopHL.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.nodeTopHL)
        self.nodeTableWidget = QtWidgets.QTableWidget(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nodeTableWidget.setFont(font)
        self.nodeTableWidget.setObjectName("nodeTableWidget")
        self.nodeTableWidget.setColumnCount(11)
        self.nodeTableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.nodeTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodeTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodeTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodeTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.nodeTableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.nodeTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.nodeTableWidget.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.nodeTableWidget.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.nodeTableWidget.setItem(2, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.nodeTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.nodeTableWidget.setItem(3, 10, item)
        self.nodeTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.nodeTableWidget.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout_2.addWidget(self.nodeTableWidget)
        self.graphicsView = QtWidgets.QGraphicsView(self.nodeConfigTab)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.nodeMiddleHL = QtWidgets.QHBoxLayout()
        self.nodeMiddleHL.setObjectName("nodeMiddleHL")
        self.timelineLabel = QtWidgets.QLabel(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.timelineLabel.setFont(font)
        self.timelineLabel.setObjectName("timelineLabel")
        self.nodeMiddleHL.addWidget(self.timelineLabel)
        self.timelineOrientationComboBox = QtWidgets.QComboBox(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.timelineOrientationComboBox.setFont(font)
        self.timelineOrientationComboBox.setObjectName("timelineOrientationComboBox")
        self.timelineOrientationComboBox.addItem("")
        self.timelineOrientationComboBox.addItem("")
        self.nodeMiddleHL.addWidget(self.timelineOrientationComboBox)
        self.intervalUnitsLabel = QtWidgets.QLabel(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.intervalUnitsLabel.setFont(font)
        self.intervalUnitsLabel.setObjectName("intervalUnitsLabel")
        self.nodeMiddleHL.addWidget(self.intervalUnitsLabel)
        self.intervalUnitsComboBox = QtWidgets.QComboBox(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.intervalUnitsComboBox.setFont(font)
        self.intervalUnitsComboBox.setObjectName("intervalUnitsComboBox")
        self.intervalUnitsComboBox.addItem("")
        self.intervalUnitsComboBox.addItem("")
        self.intervalUnitsComboBox.addItem("")
        self.intervalUnitsComboBox.addItem("")
        self.nodeMiddleHL.addWidget(self.intervalUnitsComboBox)
        self.intervalLabel = QtWidgets.QLabel(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.intervalLabel.setFont(font)
        self.intervalLabel.setObjectName("intervalLabel")
        self.nodeMiddleHL.addWidget(self.intervalLabel)
        self.intervalSpinBox = QtWidgets.QSpinBox(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.intervalSpinBox.setFont(font)
        self.intervalSpinBox.setObjectName("intervalSpinBox")
        self.nodeMiddleHL.addWidget(self.intervalSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.nodeMiddleHL.addItem(spacerItem2)
        self.zoomInButton = QtWidgets.QPushButton(self.nodeConfigTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomInButton.sizePolicy().hasHeightForWidth())
        self.zoomInButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.zoomInButton.setFont(font)
        self.zoomInButton.setObjectName("zoomInButton")
        self.nodeMiddleHL.addWidget(self.zoomInButton)
        self.zoomOutButton = QtWidgets.QPushButton(self.nodeConfigTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomOutButton.sizePolicy().hasHeightForWidth())
        self.zoomOutButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.zoomOutButton.setFont(font)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.nodeMiddleHL.addWidget(self.zoomOutButton)
        self.verticalLayout_2.addLayout(self.nodeMiddleHL)
        self.nodeBottomHL = QtWidgets.QHBoxLayout()
        self.nodeBottomHL.setObjectName("nodeBottomHL")
        self.relationshipsButton = QtWidgets.QPushButton(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.relationshipsButton.setFont(font)
        self.relationshipsButton.setObjectName("relationshipsButton")
        self.nodeBottomHL.addWidget(self.relationshipsButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.nodeBottomHL.addItem(spacerItem3)
        self.iconButton = QtWidgets.QPushButton(self.nodeConfigTab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.iconButton.setFont(font)
        self.iconButton.setObjectName("iconButton")
        self.nodeBottomHL.addWidget(self.iconButton)
        self.addNodePushButton = QtWidgets.QPushButton(self.nodeConfigTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addNodePushButton.sizePolicy().hasHeightForWidth())
        self.addNodePushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.addNodePushButton.setFont(font)
        self.addNodePushButton.setObjectName("addNodePushButton")
        self.nodeBottomHL.addWidget(self.addNodePushButton)
        self.editNodePushButton = QtWidgets.QPushButton(self.nodeConfigTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editNodePushButton.sizePolicy().hasHeightForWidth())
        self.editNodePushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.editNodePushButton.setFont(font)
        self.editNodePushButton.setObjectName("editNodePushButton")
        self.nodeBottomHL.addWidget(self.editNodePushButton)
        self.deleteNodePushButton = QtWidgets.QPushButton(self.nodeConfigTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteNodePushButton.sizePolicy().hasHeightForWidth())
        self.deleteNodePushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.deleteNodePushButton.setFont(font)
        self.deleteNodePushButton.setObjectName("deleteNodePushButton")
        self.nodeBottomHL.addWidget(self.deleteNodePushButton)
        self.verticalLayout_2.addLayout(self.nodeBottomHL)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.tabWidget.addTab(self.nodeConfigTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.mainWidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 949, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.teamButton.setText(_translate("mainWindow", "Team"))
        self.eventButton.setText(_translate("mainWindow", "Event"))
        self.vectorButton.setText(_translate("mainWindow", "Vector"))
        self.filterButton.setText(_translate("mainWindow", "Filter"))
        self.commitButton.setText(_translate("mainWindow", "Commit"))
        self.syncButton.setText(_translate("mainWindow", "Sync"))
        self.exportButton.setText(_translate("mainWindow", "Export"))
        self.logFileTableLabel.setText(_translate("mainWindow", "Log Files"))
        self.logFileTable.setSortingEnabled(True)
        item = self.logFileTable.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "1"))
        item = self.logFileTable.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "2"))
        item = self.logFileTable.verticalHeaderItem(2)
        item.setText(_translate("mainWindow", "3"))
        item = self.logFileTable.verticalHeaderItem(3)
        item.setText(_translate("mainWindow", "4"))
        item = self.logFileTable.verticalHeaderItem(4)
        item.setText(_translate("mainWindow", "5"))
        item = self.logFileTable.verticalHeaderItem(5)
        item.setText(_translate("mainWindow", "6"))
        item = self.logFileTable.verticalHeaderItem(6)
        item.setText(_translate("mainWindow", "7"))
        item = self.logFileTable.verticalHeaderItem(7)
        item.setText(_translate("mainWindow", "8"))
        item = self.logFileTable.verticalHeaderItem(8)
        item.setText(_translate("mainWindow", "9"))
        item = self.logFileTable.verticalHeaderItem(9)
        item.setText(_translate("mainWindow", "10"))
        item = self.logFileTable.verticalHeaderItem(10)
        item.setText(_translate("mainWindow", "11"))
        item = self.logFileTable.verticalHeaderItem(11)
        item.setText(_translate("mainWindow", "12"))
        item = self.logFileTable.verticalHeaderItem(12)
        item.setText(_translate("mainWindow", "13"))
        item = self.logFileTable.verticalHeaderItem(13)
        item.setText(_translate("mainWindow", "14"))
        item = self.logFileTable.verticalHeaderItem(14)
        item.setText(_translate("mainWindow", "15"))
        item = self.logFileTable.verticalHeaderItem(15)
        item.setText(_translate("mainWindow", "16"))
        item = self.logFileTable.verticalHeaderItem(16)
        item.setText(_translate("mainWindow", "17"))
        item = self.logFileTable.verticalHeaderItem(17)
        item.setText(_translate("mainWindow", "18"))
        item = self.logFileTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "File name"))
        item = self.logFileTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Source"))
        item = self.logFileTable.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Cleansing Status"))
        item = self.logFileTable.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Validation Status"))
        item = self.logFileTable.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Ingestion Status"))
        item = self.logFileTable.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "View EAR"))
        __sortingEnabled = self.logFileTable.isSortingEnabled()
        self.logFileTable.setSortingEnabled(False)
        self.logFileTable.setSortingEnabled(__sortingEnabled)
        self.earTableLabel.setText(_translate("mainWindow", "Enforcement Action Reports"))
        self.earTable.setSortingEnabled(True)
        item = self.earTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Line Number"))
        item = self.earTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Error Message "))
        self.chosenFileLabel.setText(_translate("mainWindow", "File Name:"))
        self.chosenFilePathLabel.setText(_translate("mainWindow", "C:<pathtofile>"))
        self.directoryButton.setText(_translate("mainWindow", "Directory"))
        self.validateButton.setText(_translate("mainWindow", "Validate"))
        self.cancelButton.setText(_translate("mainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logFileTab), _translate("mainWindow", "Log File Configuration"))
        item = self.logEntryTableWidget.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "1"))
        item = self.logEntryTableWidget.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "2"))
        item = self.logEntryTableWidget.verticalHeaderItem(2)
        item.setText(_translate("mainWindow", "3"))
        item = self.logEntryTableWidget.verticalHeaderItem(3)
        item.setText(_translate("mainWindow", "4"))
        item = self.logEntryTableWidget.verticalHeaderItem(4)
        item.setText(_translate("mainWindow", "5"))
        item = self.logEntryTableWidget.verticalHeaderItem(5)
        item.setText(_translate("mainWindow", "6"))
        item = self.logEntryTableWidget.verticalHeaderItem(6)
        item.setText(_translate("mainWindow", "7"))
        item = self.logEntryTableWidget.verticalHeaderItem(7)
        item.setText(_translate("mainWindow", "8"))
        item = self.logEntryTableWidget.verticalHeaderItem(8)
        item.setText(_translate("mainWindow", "9"))
        item = self.logEntryTableWidget.verticalHeaderItem(9)
        item.setText(_translate("mainWindow", "10"))
        item = self.logEntryTableWidget.verticalHeaderItem(10)
        item.setText(_translate("mainWindow", "11"))
        item = self.logEntryTableWidget.verticalHeaderItem(11)
        item.setText(_translate("mainWindow", "12"))
        item = self.logEntryTableWidget.verticalHeaderItem(12)
        item.setText(_translate("mainWindow", "13"))
        item = self.logEntryTableWidget.verticalHeaderItem(13)
        item.setText(_translate("mainWindow", "14"))
        item = self.logEntryTableWidget.verticalHeaderItem(14)
        item.setText(_translate("mainWindow", "15"))
        item = self.logEntryTableWidget.verticalHeaderItem(15)
        item.setText(_translate("mainWindow", "16"))
        item = self.logEntryTableWidget.verticalHeaderItem(16)
        item.setText(_translate("mainWindow", "17"))
        item = self.logEntryTableWidget.verticalHeaderItem(17)
        item.setText(_translate("mainWindow", "18"))
        item = self.logEntryTableWidget.verticalHeaderItem(18)
        item.setText(_translate("mainWindow", "20"))
        item = self.logEntryTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Include"))
        item = self.logEntryTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "List Number"))
        item = self.logEntryTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Log Entry Timestamp"))
        item = self.logEntryTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Log Entry Event"))
        item = self.logEntryTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Vector"))
        __sortingEnabled = self.logEntryTableWidget.isSortingEnabled()
        self.logEntryTableWidget.setSortingEnabled(False)
        self.logEntryTableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ogEntryTab), _translate("mainWindow", "Log Entry Configuration"))
        self.vectorLabel.setText(_translate("mainWindow", "Vector:"))
        self.vectorComboBox.setItemText(0, _translate("mainWindow", "SQL Injection"))
        self.vectorComboBox.setItemText(1, _translate("mainWindow", "Denial-of-Service"))
        self.descriptionLabel.setText(_translate("mainWindow", "Description:"))
        self.label.setText(_translate("mainWindow", "<Description>"))
        item = self.nodeTableWidget.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "Node Visibility Property"))
        item = self.nodeTableWidget.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "1"))
        item = self.nodeTableWidget.verticalHeaderItem(2)
        item.setText(_translate("mainWindow", "2"))
        item = self.nodeTableWidget.verticalHeaderItem(3)
        item.setText(_translate("mainWindow", "3"))
        item = self.nodeTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Select"))
        item = self.nodeTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Node ID"))
        item = self.nodeTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Node Name"))
        item = self.nodeTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Node Timestamp"))
        item = self.nodeTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Node Description"))
        item = self.nodeTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Log Entry Reference"))
        item = self.nodeTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Log Creator"))
        item = self.nodeTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "Event Type"))
        item = self.nodeTableWidget.horizontalHeaderItem(8)
        item.setText(_translate("mainWindow", "Icon Type"))
        item = self.nodeTableWidget.horizontalHeaderItem(9)
        item.setText(_translate("mainWindow", "Source"))
        item = self.nodeTableWidget.horizontalHeaderItem(10)
        item.setText(_translate("mainWindow", "Node Visibility"))
        __sortingEnabled = self.nodeTableWidget.isSortingEnabled()
        self.nodeTableWidget.setSortingEnabled(False)
        self.nodeTableWidget.setSortingEnabled(__sortingEnabled)
        self.timelineLabel.setText(_translate("mainWindow", "Timeline Orientation:"))
        self.timelineOrientationComboBox.setItemText(0, _translate("mainWindow", "Horizontal"))
        self.timelineOrientationComboBox.setItemText(1, _translate("mainWindow", "Vertical"))
        self.intervalUnitsLabel.setText(_translate("mainWindow", "Interval Units:"))
        self.intervalUnitsComboBox.setItemText(0, _translate("mainWindow", "Days"))
        self.intervalUnitsComboBox.setItemText(1, _translate("mainWindow", "Hours"))
        self.intervalUnitsComboBox.setItemText(2, _translate("mainWindow", "Minutes"))
        self.intervalUnitsComboBox.setItemText(3, _translate("mainWindow", "Seconds"))
        self.intervalLabel.setText(_translate("mainWindow", "Interval:"))
        self.zoomInButton.setText(_translate("mainWindow", "Zoom In"))
        self.zoomOutButton.setText(_translate("mainWindow", "Zoom Out"))
        self.relationshipsButton.setText(_translate("mainWindow", "Relationships"))
        self.iconButton.setText(_translate("mainWindow", "Icon"))
        self.addNodePushButton.setText(_translate("mainWindow", "Add node"))
        self.editNodePushButton.setText(_translate("mainWindow", "Edit node"))
        self.deleteNodePushButton.setText(_translate("mainWindow", "Delete node"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nodeConfigTab), _translate("mainWindow", "Node Configuration"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))

    def show_team_dialog(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = teamConfigDialog()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()

    def show_event_dialog(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = eventConfigDialog()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()

    def show_filter_dialog(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = filter_dialog()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
