# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/team_configuration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teamConfigDialog(object):
    def setupUi(self, teamConfigDialog):
        teamConfigDialog.setObjectName("teamConfigDialog")
        teamConfigDialog.resize(522, 143)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(teamConfigDialog.sizePolicy().hasHeightForWidth())
        teamConfigDialog.setSizePolicy(sizePolicy)
        teamConfigDialog.setMinimumSize(QtCore.QSize(522, 143))
        teamConfigDialog.setMaximumSize(QtCore.QSize(522, 143))
        self.verticalLayout = QtWidgets.QVBoxLayout(teamConfigDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topHL = QtWidgets.QHBoxLayout()
        self.topHL.setObjectName("topHL")
        self.leadCheckBox = QtWidgets.QCheckBox(teamConfigDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.leadCheckBox.setFont(font)
        self.leadCheckBox.setStyleSheet("")
        self.leadCheckBox.setObjectName("leadCheckBox")
        self.topHL.addWidget(self.leadCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topHL.addItem(spacerItem)
        self.yourIPLabel = QtWidgets.QLabel(teamConfigDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.yourIPLabel.setFont(font)
        self.yourIPLabel.setObjectName("yourIPLabel")
        self.topHL.addWidget(self.yourIPLabel)
        self.yourIPNumberLabel = QtWidgets.QLabel(teamConfigDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.yourIPNumberLabel.setFont(font)
        self.yourIPNumberLabel.setObjectName("yourIPNumberLabel")
        self.topHL.addWidget(self.yourIPNumberLabel)
        self.verticalLayout.addLayout(self.topHL)
        self.middleHL = QtWidgets.QHBoxLayout()
        self.middleHL.setObjectName("middleHL")
        self.establishedConnectionsLabel = QtWidgets.QLabel(teamConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.establishedConnectionsLabel.sizePolicy().hasHeightForWidth())
        self.establishedConnectionsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.establishedConnectionsLabel.setFont(font)
        self.establishedConnectionsLabel.setStyleSheet("")
        self.establishedConnectionsLabel.setObjectName("establishedConnectionsLabel")
        self.middleHL.addWidget(self.establishedConnectionsLabel)
        self.establishedConnectionsNumberLabel = QtWidgets.QLabel(teamConfigDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.establishedConnectionsNumberLabel.setFont(font)
        self.establishedConnectionsNumberLabel.setStyleSheet("")
        self.establishedConnectionsNumberLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.establishedConnectionsNumberLabel.setObjectName("establishedConnectionsNumberLabel")
        self.middleHL.addWidget(self.establishedConnectionsNumberLabel)
        self.verticalLayout.addLayout(self.middleHL)
        self.bottomHL = QtWidgets.QHBoxLayout()
        self.bottomHL.setObjectName("bottomHL")
        self.leadIPLabel = QtWidgets.QLabel(teamConfigDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.leadIPLabel.setFont(font)
        self.leadIPLabel.setObjectName("leadIPLabel")
        self.bottomHL.addWidget(self.leadIPLabel)
        self.leadIPText = QtWidgets.QLineEdit(teamConfigDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.leadIPText.setFont(font)
        self.leadIPText.setObjectName("leadIPText")
        self.bottomHL.addWidget(self.leadIPText)
        self.verticalLayout.addLayout(self.bottomHL)
        self.connectButton = QtWidgets.QPushButton(teamConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.connectButton.setFont(font)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout.addWidget(self.connectButton, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(teamConfigDialog)
        QtCore.QMetaObject.connectSlotsByName(teamConfigDialog)

    def retranslateUi(self, teamConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        teamConfigDialog.setWindowTitle(_translate("teamConfigDialog", "Team Configuration"))
        self.leadCheckBox.setText(_translate("teamConfigDialog", "Lead"))
        self.yourIPLabel.setText(_translate("teamConfigDialog", "Your IP address:"))
        self.yourIPNumberLabel.setText(_translate("teamConfigDialog", "192.168.0.1"))
        self.establishedConnectionsLabel.setText(_translate("teamConfigDialog", "No. of established connections to the lead’s IP address:"))
        self.establishedConnectionsNumberLabel.setText(_translate("teamConfigDialog", "2"))
        self.leadIPLabel.setText(_translate("teamConfigDialog", "Lead IP address:"))
        self.connectButton.setText(_translate("teamConfigDialog", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teamConfigDialog = QtWidgets.QDialog()
    ui = Ui_teamConfigDialog()
    ui.setupUi(teamConfigDialog)
    teamConfigDialog.show()
    sys.exit(app.exec_())
