# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/vector_db_configuration_lead.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class vector_db_lead(object):
    def setupUi(self, vectorDBConfigLeadFrame):
        vectorDBConfigLeadFrame.setObjectName("vectorDBConfigLeadFrame")
        vectorDBConfigLeadFrame.resize(859, 351)
        vectorDBConfigLeadFrame.setMinimumSize(QtCore.QSize(720, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(vectorDBConfigLeadFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(vectorDBConfigLeadFrame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget.setItem(2, 0, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButton = QtWidgets.QPushButton(vectorDBConfigLeadFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(vectorDBConfigLeadFrame)
        QtCore.QMetaObject.connectSlotsByName(vectorDBConfigLeadFrame)

    def retranslateUi(self, vectorDBConfigLeadFrame):
        _translate = QtCore.QCoreApplication.translate
        vectorDBConfigLeadFrame.setWindowTitle(_translate("vectorDBConfigLeadFrame", "Approval Sync"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("vectorDBConfigLeadFrame", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("vectorDBConfigLeadFrame", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("vectorDBConfigLeadFrame", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("vectorDBConfigLeadFrame", "Select"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("vectorDBConfigLeadFrame", "Source IP"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("vectorDBConfigLeadFrame", "Request Timestamp"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("vectorDBConfigLeadFrame", "Vector"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("vectorDBConfigLeadFrame", "Description"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("vectorDBConfigLeadFrame", "Graph"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("vectorDBConfigLeadFrame", "Change Summary"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("vectorDBConfigLeadFrame", "Sync Status"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("vectorDBConfigLeadFrame", "Commit"))

