# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/vector_db_configuration_analyst.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class vector_db_analyst(object):
    def setupUi(self, vector_db_analyst):
        vector_db_analyst.setObjectName("vector_db_analyst")
        vector_db_analyst.resize(720, 480)
        vector_db_analyst.setMinimumSize(QtCore.QSize(720, 480))
        self.verticalLayout = QtWidgets.QVBoxLayout(vector_db_analyst)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(vector_db_analyst)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(vector_db_analyst)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(vector_db_analyst)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(vector_db_analyst)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(vector_db_analyst)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget.setItem(2, 0, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(vector_db_analyst)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(vector_db_analyst)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableWidget_2 = QtWidgets.QTableWidget(vector_db_analyst)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_2.setItem(2, 0, item)
        self.verticalLayout.addWidget(self.tableWidget_2)

        self.retranslateUi(vector_db_analyst)
        QtCore.QMetaObject.connectSlotsByName(vector_db_analyst)

    def retranslateUi(self, vector_db_analyst):
        _translate = QtCore.QCoreApplication.translate
        vector_db_analyst.setWindowTitle(_translate("vector_db_analyst", "Vector DB Sync"))
        self.label.setText(_translate("vector_db_analyst", "Connection Status to Lead:"))
        self.label_2.setText(_translate("vector_db_analyst", "Not Connected"))
        self.label_3.setText(_translate("vector_db_analyst", "Pulled Vector DB Table (Analyst)"))
        self.pushButton.setText(_translate("vector_db_analyst", "Pull"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("vector_db_analyst", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("vector_db_analyst", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("vector_db_analyst", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("vector_db_analyst", "Select"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("vector_db_analyst", "Vector"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("vector_db_analyst", "Description"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("vector_db_analyst", "Graph"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("vector_db_analyst", "Pushed Vector DB Table (Analyst)"))
        self.pushButton_2.setText(_translate("vector_db_analyst", "Push"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("vector_db_analyst", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("vector_db_analyst", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("vector_db_analyst", "3"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("vector_db_analyst", "Select"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("vector_db_analyst", "Vector"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("vector_db_analyst", "Description"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("vector_db_analyst", "Graph"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)

