# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/vector_configuration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class vectorConfigFrame(object):
    def setupUi(self, vectorConfigFrame):
        vectorConfigFrame.setObjectName("vectorConfigFrame")
        vectorConfigFrame.resize(524, 225)
        vectorConfigFrame.setMinimumSize(QtCore.QSize(524, 150))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        vectorConfigFrame.setFont(font)
        vectorConfigFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        vectorConfigFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(vectorConfigFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vectorTableWidget = QtWidgets.QTableWidget(vectorConfigFrame)
        self.vectorTableWidget.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.vectorTableWidget.setFont(font)
        self.vectorTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.vectorTableWidget.setColumnCount(3)
        self.vectorTableWidget.setObjectName("vectorTableWidget")
        self.vectorTableWidget.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        item.setFont(font)
        self.vectorTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.vectorTableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.vectorTableWidget.setItem(14, 0, item)
        self.vectorTableWidget.verticalHeader().setVisible(True)
        self.vectorTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.vectorTableWidget.verticalHeader().setDefaultSectionSize(30)
        self.vectorTableWidget.verticalHeader().setHighlightSections(False)
        self.vectorTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.vectorTableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.vectorTableWidget)
        self.buttonHL = QtWidgets.QHBoxLayout()
        self.buttonHL.setObjectName("buttonHL")
        self.addVectorButton = QtWidgets.QPushButton(vectorConfigFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addVectorButton.sizePolicy().hasHeightForWidth())
        self.addVectorButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.addVectorButton.setFont(font)
        self.addVectorButton.setObjectName("addVectorButton")
        self.buttonHL.addWidget(self.addVectorButton)
        self.deleteVectorButton = QtWidgets.QPushButton(vectorConfigFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteVectorButton.sizePolicy().hasHeightForWidth())
        self.deleteVectorButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.deleteVectorButton.setFont(font)
        self.deleteVectorButton.setObjectName("deleteVectorButton")
        self.buttonHL.addWidget(self.deleteVectorButton)
        self.editVectorButton = QtWidgets.QPushButton(vectorConfigFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editVectorButton.sizePolicy().hasHeightForWidth())
        self.editVectorButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.editVectorButton.setFont(font)
        self.editVectorButton.setObjectName("editVectorButton")
        self.buttonHL.addWidget(self.editVectorButton)
        self.verticalLayout.addLayout(self.buttonHL)

        self.retranslateUi(vectorConfigFrame)
        QtCore.QMetaObject.connectSlotsByName(vectorConfigFrame)

    def retranslateUi(self, vectorConfigFrame):
        _translate = QtCore.QCoreApplication.translate
        vectorConfigFrame.setWindowTitle(_translate("vectorConfigFrame", "Vector Configuration"))
        item = self.vectorTableWidget.verticalHeaderItem(0)
        item.setText(_translate("vectorConfigFrame", "1"))
        item = self.vectorTableWidget.verticalHeaderItem(1)
        item.setText(_translate("vectorConfigFrame", "2"))
        item = self.vectorTableWidget.verticalHeaderItem(2)
        item.setText(_translate("vectorConfigFrame", "3"))
        item = self.vectorTableWidget.verticalHeaderItem(3)
        item.setText(_translate("vectorConfigFrame", "4"))
        item = self.vectorTableWidget.verticalHeaderItem(4)
        item.setText(_translate("vectorConfigFrame", "5"))
        item = self.vectorTableWidget.verticalHeaderItem(5)
        item.setText(_translate("vectorConfigFrame", "6"))
        item = self.vectorTableWidget.verticalHeaderItem(6)
        item.setText(_translate("vectorConfigFrame", "7"))
        item = self.vectorTableWidget.verticalHeaderItem(7)
        item.setText(_translate("vectorConfigFrame", "8"))
        item = self.vectorTableWidget.verticalHeaderItem(8)
        item.setText(_translate("vectorConfigFrame", "9"))
        item = self.vectorTableWidget.verticalHeaderItem(9)
        item.setText(_translate("vectorConfigFrame", "10"))
        item = self.vectorTableWidget.verticalHeaderItem(10)
        item.setText(_translate("vectorConfigFrame", "11"))
        item = self.vectorTableWidget.verticalHeaderItem(11)
        item.setText(_translate("vectorConfigFrame", "12"))
        item = self.vectorTableWidget.verticalHeaderItem(12)
        item.setText(_translate("vectorConfigFrame", "13"))
        item = self.vectorTableWidget.verticalHeaderItem(13)
        item.setText(_translate("vectorConfigFrame", "14"))
        item = self.vectorTableWidget.verticalHeaderItem(14)
        item.setText(_translate("vectorConfigFrame", "15"))
        item = self.vectorTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("vectorConfigFrame", "Include"))
        item = self.vectorTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("vectorConfigFrame", "Vector Name"))
        item = self.vectorTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("vectorConfigFrame", "Description"))
        __sortingEnabled = self.vectorTableWidget.isSortingEnabled()
        self.vectorTableWidget.setSortingEnabled(False)
        self.vectorTableWidget.setSortingEnabled(__sortingEnabled)
        self.addVectorButton.setText(_translate("vectorConfigFrame", "Add Vector"))
        self.deleteVectorButton.setText(_translate("vectorConfigFrame", "Delete Vector"))
        self.editVectorButton.setText(_translate("vectorConfigFrame", "Edit Vector"))

